[package]
name = "unsourcemap"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
serde = "1.0.209"
serde_derive = "1.0.209"
serde_json = "1.0.127"
thiserror = "1.0.63"
